spring:
  application:
    name: zuul

server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    microsinger:
      path: /singer/**
      serviceId: microsinger
      strip-prefix: false
    albums: 
      path: /album/**
      serviceId: microsinger
      strip-prefix: false
    instrumentos:
      path: /instrument/**
      serviceId: instrumentos
      strip-prefix: false
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

endpoints:
  trace:
    sensitive: false
