spring:
  application:
    name: zuul

server:
  port: 8000
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

endpoints:
  trace:
    sensitive: false
    
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    microinstrument:
      serviceId: microinstrument
      path: /instrument/**
      strip-prefix: false
    microsinger:
      serviceId: microsinger
      path: /singer/**
      strip-prefix: false
    albums: 
      serviceId: microsinger
      path: /album/**
      strip-prefix: false
    
